name: Deploy Registry Service to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permette di far partire il deploy anche manualmente dal sito GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Fondamentale per la Workload Identity Federation

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Usiamo gli stessi secrets che già usi nel mail-reader
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ssg-registry-service
          region: europe-west8 # Allineato al mail-reader
          source: .            # GCP farà la build Docker in automatico usando il nostro Dockerfile
          flags: |
            --port=8080
            --ingress=internal-and-cloud-load-balancing
          env_vars: |
           ENV=production
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            GATEWAY_URL=${{ secrets.GATEWAY_URL }}
            SERVICE_URL=${{ secrets.SERVICE_URL }}
            INTERNAL_SECRET=${{ secrets.INTERNAL_SECRET }}